### ISSUE TITLE
Users can have a list of doctors available, along with their contact information in-case of emergencies

### ISSUE THREAD

**Issue by muhammedumar17** [AKalyanPavan/MedTracker#9]
As a user, I want to **maintain a list of doctors with their contact information within the app**, so that I have quick access to emergency contacts in case of any medical issues.

**Comment by AKalyanPavan** [comment]
As suggested by the professor, it's not a feasible solution to store some sample data in a Firebase and show it to user. The data has to be realtime. Hence we are closing the issue.
